In [3]:
import numpy as np
np_array = np.arange(1,11)

In [4]:
np_array.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
array1=np.ones((3,5),dtype = np.uint8)
array1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [6]:
import time
array_size = 3

python_list1 = list(range(array_size))
python_list2 = list(range(array_size))
print(python_list1)
result_generator = [x*y for x, y in zip(python_list1,python_list2)]
for product in result_generator:
    print(product)

print(list(result_generator))

[0, 1, 2]
0
1
4
[0, 1, 4]


In [7]:
from numpy import savetxt

np_array1 = np.arange(1,11)
array2 = np_array1.reshape(2,5)
print(array2)
savetxt("array2.csv",array2,delimiter = ",")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
from numpy import loadtxt

array3 = loadtxt("array2.csv",delimiter = ",")
print(array3.astype(np.float16))
array7=array3.ravel()
array7.astype(np.uint8)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=uint8)

In [9]:
array4 = np.full((3,3),5)
array6 = np.ones((3,3))
array9 = array6.copy()
array9

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
def my_function(z,y,x):
    return x*y+z

np.fromfunction(my_function,(3,2,10)) 
#The code np.fromfunction(my_function, (3, 2, 10)) constructs a NumPy array with shape (3, 2, 10) by executing my_function for each coordinate. 

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],

       [[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
        [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]]])

In [11]:
matrix1 = np.arange(1,21).reshape(4,5)
matrix1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
matrix1[1:3,2:4]
# matrix1[:,2]
matrix1[[2],[3]]


array([14])

In [13]:
matrix2 = np.arange(0,15).reshape(3,5)
print(matrix2[matrix2>10])

[11 12 13 14]


In [14]:
# Original array
a = np.arange(16).reshape(4, 4)
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11],
#        [12, 13, 14, 15]])

# Indices for desired rows and columns
row_indices = [0, 2]
col_indices = [0, 2]

# Using np.ix_ for selection
submatrix = a[np.ix_(row_indices, col_indices)]

print(submatrix)
# Output:
# array([[ 0,  2],
#        [ 8, 10]])

[[ 0  2]
 [ 8 10]]


In [15]:
m = np.arange(0,45).reshape(3,3,5)
m[1][(0,2),1:5]=1
m[m%2==1]=1
m[m%2==0]=0
m1=m.reshape(9,5)
m1

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0],
       [1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [16]:
matrix1 = np.arange(1,21).reshape(4,5)
print(matrix1)
print(matrix1.T)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [17]:
coeff = np.array([[2,6],[5,3]])
result= np.array([6,-9])
solution = np.linalg.solve(coeff,result)
print(solution)

[-3.  2.]


In [18]:
m1 = np.arange(15).reshape(3,5)
m2 = np.arange(15).reshape(5,3)
m = m1.dot(m2)
m=np.sqrt(m)
m.sum()

np.float64(143.2015963354727)

In [19]:
m4 = np.arange(24).reshape(2,3,4)
print(m4)
m5 = np.transpose(m4,(2,0,1)) #.shape from 2,3,4 -> 4,2,3
m6 = m4.transpose(2,0,1) 
m6

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [20]:
# np.vstack (m1,m2)
# np.concatenate(m1,m2, axis=0) 

# m1,m2,m3 = np.vsplit(big_matrix,3)

# m2 = np.tile(m1,(4,2)) #4:the first dimension repeated 4 times(horizontal), 2: then 2nd dim repeated 2 times



In [24]:
#broadcasting

a = np.array([0,10,20,30])
b= np.array([0,1,2])

# print(a+b) #ValueError: operands could not be broadcast together with shapes (4,) (3,) 

c = a[:,None] #This operation selects all elements along the existing axis (: in the first position) and adds a new axis in the second position (None).
# a.shape is (4,) 
# a is [0, 10, 20, 30]
# c.shape becomes (4, 1)
# c is [[0], [10], [20], [30]] 

print(c)

print(c+b)

[[ 0]
 [10]
 [20]
 [30]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [41]:
a = np.array([0,10,20,30])
b= np.array([[0,1],[0,1],[0,1]])
c = a[:,None]
d=np.array([[5,6]])
e=np.array([[1,2,3],[1,2,3]])
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape)
print(b+d)
print(e+d)

(4,)
(3, 2)
(4, 1)
(1, 2)
(2, 3)
[[5 7]
 [5 7]
 [5 7]]


ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 